### ISSUE TITLE
The template validation failed

### ISSUE THREAD

**Issue by shyang-oblab** [OfficeDev/msteams-sample-line-of-business-apps-csharp#59]
Microsoft Flow Error with 'Connector Card JSON payload.json'

ref.
https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Building-low-code-no-code-approval-workflows-for-your-team-using/ba-p/376414

The template validation failed: 'The template action 'HTTP' at line '1' and column '1662' is not valid: "Unable to parse template language expression 'type': expected token 'LeftParenthesis' and actual 'EndOfData'.".'.

**Comment by Wajeed-msft** [comment]
@shyang-oblab - Could you please replace @ with @@ because @ is reserved for dynamic content. 
![image](https://user-images.githubusercontent.com/31851992/56290548-01a6fc00-6141-11e9-8f9f-0b4d1bb0ab40.png)


Sample content: https://github.com/OfficeDev/msteams-sample-line-of-business-apps-csharp/blob/master/Cross%20Vertical/Low%20Code%20No%20Code%20Approvals/Connector%20Card%20JSON%20payload.json

**Comment by shyang-oblab** [comment]
Thank you for your quick reply.
I just have solved, too.
